### ISSUE TITLE
Can't create d3tree from treemap object

### ISSUE THREAD

**Issue by Quiri** [timelyportfolio/d3treeR#15] opened 2015-08-31 11:47 UTC
```
d3tree2(tree, rootname = "all")
```

where tree is a valid treemap object gives me this error:

```
Error in convert_treemap(data$tm, ifelse(!is.null(rootname), rootname,  : 
  could not find function "as.Node"
```

Any ideas?

**Comment by timelyportfolio** [comment] 2015-08-31 11:58
`data.tree` has changed quite a bit recently.  If possible, try `devtools::install_github("gluc/data.tree")` and see if that fixes it.

**Comment by debugpoint136** [comment] 2015-09-03 15:00
I am facing the same issue. I tried installing data.tree. Now I get this error:
```
Error in convert_treemap(data$tm, ifelse(!is.null(rootname), rootname,  : 
  attempt to apply non-function
```

Any suggestions? Thanks!

**Comment by timelyportfolio** [comment] 2015-09-03 15:04
Please provide a full reproducible example, and I'll be happy to take a look.  Glad you are trying it out.

**Comment by debugpoint136** [comment] 2015-09-03 16:48
Restarted Rstudio - installed data.tree again. Works now. Thanks!  this is super useful - thanks for writing this..

**Comment by timelyportfolio** [comment] 2018-02-06 14:16
closing this since issue seems resolved.

**Closed by timelyportfolio** 2018-02-06 14:16 UTC
